version: '3.8'

networks:
 net:
  driver: bridge

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: pgsql
      POSTGRES_DB: read_DB
    ports:
      - 5432:5432

  mssql:
    image: "judahh/mssql-image:latest"
    ports:
    - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: yourStrong(!)Password
      MSSQL_PID: Developer
      DATABASE_NAME: read_DB
