version: '3.8'

networks:
 net:
  driver: bridge

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: pgsql
      POSTGRES_DB: read_DB
    ports:
      - 5432:5432

  mssql:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
    - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: yourStrong(!)Password
      MSSQL_PID: Developer
  minion:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
    - mssql
    command: >
      sh -c "
      echo 'START' &&
      echo sleep 60 &&
      /opt/mssql-tools/bin/sqlcmd -S mssql -U SA -P 'yourStrong(!)Password'
      -Q 'CREATE DATABASE read_DB' &&
      echo 'END'
      "
